import { createHash } from "crypto";
import {
  createReadStream,
  createWriteStream,
  statSync,
  existsSync,
  writeFileSync,
  readFileSync,
  unlinkSync,
} from "fs";
import { readdir } from "fs/promises";
import { tmpdir } from "os";
import { join, resolve, relative } from "path";
import { formatBytes, uploadToPresignedUrl } from "./util";
import archiver from "archiver";
import axios from "axios";
import ignore from "ignore";
import beamClient from "./index";

// Global workspace object id to signal to any other threads that the workspace has already been synced
let _workspaceObjectId = "";
let _syncLock = false;

export function setWorkspaceObjectId(objectId: string): void {
  _workspaceObjectId = objectId;
}

export function getWorkspaceObjectId(): string {
  return _workspaceObjectId || "";
}

function ignoreFileName(): string {
  return ".beamignore";
}

function ignoreFileContents(): string {
  return `# Generated by Beam SDK
.beamignore
pyproject.toml
.git
.idea
.python-version
.vscode
.DS_Store
.config
drive/MyDrive
.coverage
*.ipynb
.ruff_cache
.dockerignore
.ipynb_checkpoints
.env.local
.envrc
**/__pycache__/
**/.pytest_cache/
**/node_modules/
**/.venv/
*.pyc
.next/
.circleci
`;
}

export interface ObjectMetadata {
  name: string;
  size: number;
}

export interface CreateObjectRequest {
  objectMetadata: ObjectMetadata;
  hash: string;
  size: number;
  overwrite: boolean;
}

export interface CreateObjectResponse {
  ok: boolean;
  objectId: string;
  presignedUrl: string;
}

export interface HeadObjectRequest {
  hash: string;
}

export interface HeadObjectResponse {
  exists: boolean;
  ok: boolean;
  objectId: string;
  objectMetadata: any | null;
  errorMsg: string;
  useWorkspaceStorage: boolean;
}

export interface PutObjectRequest {
  chunk: Buffer;
  metadata: ObjectMetadata;
  hash: string;
  isFinal: boolean;
}

export interface FileSyncResult {
  success: boolean;
  objectId: string;
}

export class FileSyncer {
  private rootDir: string;
  private isWorkspaceDir: boolean;
  private ignorePatterns: string[] = [];
  private includePatterns: string[] = [];
  private ignoreSpec: ReturnType<typeof ignore> | null = null;
  private includeSpec: ReturnType<typeof ignore> | null = null;

  constructor(rootDir: string = ".") {
    this.rootDir = resolve(rootDir);
    this.isWorkspaceDir = rootDir === ".";
  }

  private get ignoreFilePath(): string {
    return join(this.rootDir, ignoreFileName());
  }

  private initIgnoreFile(): void {
    if (existsSync(this.ignoreFilePath)) {
      return;
    }

    console.log(`Writing ${ignoreFileName()} file`);
    writeFileSync(this.ignoreFilePath, ignoreFileContents());
  }

  private readIgnoreFile(): string[] {
    console.log(`Reading ${ignoreFileName()} file`);

    const patterns: string[] = [];

    if (existsSync(this.ignoreFilePath)) {
      const content = readFileSync(this.ignoreFilePath, "utf-8");
      return content
        .split("\n")
        .map((line) => line.trim())
        .filter((line) => line && !line.startsWith("#"));
    }

    return patterns;
  }

  private getIgnoreSpec(): ReturnType<typeof ignore> {
    if (!this.ignoreSpec) {
      this.ignoreSpec = ignore().add(this.ignorePatterns);
    }
    return this.ignoreSpec;
  }

  private getIncludeSpec(): ReturnType<typeof ignore> {
    if (!this.includeSpec) {
      this.includeSpec = ignore().add(this.includePatterns);
    }
    return this.includeSpec;
  }

  private shouldIgnore(filePath: string, isDirectory: boolean = false): boolean {
    const relativePath = relative(this.rootDir, filePath);
    // node-ignore requires trailing slash for directories
    const pathToTest = isDirectory ? relativePath + "/" : relativePath;
    return this.getIgnoreSpec().ignores(pathToTest);
  }

  private shouldInclude(filePath: string, isDirectory: boolean = false): boolean {
    if (this.includePatterns.length === 0) {
      return true;
    }

    const relativePath = relative(this.rootDir, filePath);
    // node-ignore requires trailing slash for directories
    const pathToTest = isDirectory ? relativePath + "/" : relativePath;
    return this.getIncludeSpec().ignores(pathToTest);
  }

  private async *collectFiles(): AsyncGenerator<string> {
    if (this.ignorePatterns.includes("*")) {
      return;
    }

    console.log(`Collecting files from ${this.rootDir}`);

    const walk = async (dir: string): Promise<string[]> => {
      const files: string[] = [];
      try {
        const entries = await readdir(dir, { withFileTypes: true });

        for (const entry of entries) {
          const fullPath = join(dir, entry.name);

          if (entry.isDirectory()) {
            // Pass isDirectory=true for directory checking
            if (!this.shouldIgnore(fullPath, true)) {
              const subFiles = await walk(fullPath);
              files.push(...subFiles);
            }
          } else if (entry.isFile()) {
            // Files don't need the directory flag
            if (!this.shouldIgnore(fullPath, false) && this.shouldInclude(fullPath, false)) {
              files.push(fullPath);
            }
          }
        }
      } catch (error) {
        console.warn(`Failed to read directory ${dir}: ${error}`);
      }
      return files;
    };

    const allFiles = await walk(this.rootDir);
    for (const file of allFiles) {
      yield file;
    }
  }

  private static calculateSha256(filePath: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const hash = createHash("sha256");
      const stream = createReadStream(filePath);

      stream.on("error", reject);
      stream.on("data", (chunk) => hash.update(chunk));
      stream.on("end", () => resolve(hash.digest("hex")));
    });
  }

  private async createZipFile(): Promise<{
    filePath: string;
    size: number;
    hash: string;
  }> {
    const tempZipPath = join(tmpdir(), `beam-sync-${Date.now()}.zip`);
    const output = createWriteStream(tempZipPath);
    const archive = archiver("zip", {
      zlib: { level: 9 }, // Maximum compression
      forceLocalTime: true, // Better compatibility
      store: false, // Always compress
    });

    let totalFiles = 0;
    let processedFiles = 0;

    // Enhanced event handling
    archive.on("error", (err) => {
      console.error("Archive error:", err);
      throw err;
    });

    archive.on("warning", (err) => {
      if (err.code === "ENOENT") {
        console.warn("File not found (skipping):", err.path);
      } else {
        console.warn("Archive warning:", err);
      }
    });

    // Progress tracking
    archive.on("entry", (entry) => {
      processedFiles++;
      if (totalFiles > 0) {
        const progress = ((processedFiles / totalFiles) * 100).toFixed(1);
        console.log(
          `Progress: ${progress}% (${processedFiles}/${totalFiles}) - ${entry.name}`
        );
      }
    });

    // Handle output stream errors
    output.on("error", (err) => {
      console.error("Output stream error:", err);
      throw err;
    });

    // Pipe archive data to the file
    archive.pipe(output);

    // Count total files first for progress tracking
    const allFiles: string[] = [];
    for await (const filePath of this.collectFiles()) {
      allFiles.push(filePath);
    }
    totalFiles = allFiles.length;

    console.log(`Archiving ${totalFiles} files...`);

    for (const filePath of allFiles) {
      try {
        const relativePath = relative(this.rootDir, filePath);
        const stats = statSync(filePath);

        if (stats.isFile()) {
          archive.file(filePath, {
            name: relativePath,
            date: new Date('1980-01-01T00:00:00'), // Normalize mtime for deterministic hashing
          });
        }
      } catch (error) {
        console.warn(`Failed to add ${filePath}: ${error}`);
      }
    }

    // Finalize the archive - this triggers the actual compression
    console.log("Finalizing archive...");
    await archive.finalize();

    // Wait for the output stream to close
    await new Promise((resolve, reject) => {
      output.on("close", () => {
        console.log("Archive created successfully");
        resolve(undefined);
      });
      output.on("error", reject);
    });

    const stats = statSync(tempZipPath);
    const hash = await FileSyncer.calculateSha256(tempZipPath);

    // Log compression statistics
    const compressionRatio =
      archive.pointer() > 0
        ? ((stats.size / archive.pointer()) * 100).toFixed(1)
        : "0";
    console.log(
      `Archive stats: ${formatBytes(
        stats.size
      )} (${compressionRatio}% compression ratio)`
    );

    return {
      filePath: tempZipPath,
      size: stats.size,
      hash,
    };
  }

  private async headObject(hash: string): Promise<HeadObjectResponse> {
    const response = await beamClient.request({
      method: "GET",
      url: `/api/v1/gateway/objects/${hash}`,
    });

    return response.data;
  }

  private async createObject(
    request: CreateObjectRequest
  ): Promise<CreateObjectResponse> {
    const response = await beamClient.request({
      method: "POST",
      url: `/api/v1/gateway/objects`,
      data: request,
    });

    return response.data;
  }

  public async sync(
    ignorePatterns: string[] = [],
    includePatterns: string[] = [],
    cacheObjectId: boolean = true
  ): Promise<FileSyncResult> {
    // Simple lock mechanism
    if (_syncLock) {
      console.log("Sync already in progress");
      return { success: false, objectId: "" };
    }

    try {
      _syncLock = true;

      if (this.isWorkspaceDir && getWorkspaceObjectId() !== "") {
        console.log("Files already synced");
        return { success: true, objectId: getWorkspaceObjectId() };
      }

      return await this._sync(ignorePatterns, includePatterns, cacheObjectId);
    } finally {
      _syncLock = false;
    }
  }

  private async _sync(
    ignorePatterns: string[] = [],
    includePatterns: string[] = [],
    cacheObjectId: boolean = true
  ): Promise<FileSyncResult> {
    console.log("Syncing files");

    if (!ignorePatterns || ignorePatterns.length === 0) {
      this.initIgnoreFile();
      this.ignorePatterns = this.readIgnoreFile();
    } else {
      this.ignorePatterns = ignorePatterns;
    }

    if (!includePatterns || includePatterns.length === 0) {
      this.includePatterns = [];
    } else {
      this.includePatterns = includePatterns;
    }

    // Reset cached specs when patterns change
    this.ignoreSpec = null;
    this.includeSpec = null;

    const { filePath: tempZipPath, size, hash } = await this.createZipFile();

    if (!this.ignorePatterns.includes("*")) {
      console.log(`Collected object is ${formatBytes(size)}`);
    }

    try {
      const headResponse = await this.headObject(hash);

      if (headResponse.exists) {
        if (!headResponse.ok) {
          console.error("File sync failed");
          return { success: false, objectId: "" };
        }
        console.log("Files already synced");

        if (this.isWorkspaceDir && cacheObjectId) {
          setWorkspaceObjectId(headResponse.objectId);
        }
        return { success: true, objectId: headResponse.objectId };
      }

      const metadata: ObjectMetadata = { name: hash, size };

      if (!headResponse.useWorkspaceStorage) {
        console.error(
          "Streaming upload not implemented. Please migrate to use workspace storage. Contact support@beam.cloud for assistance."
        );
        return { success: false, objectId: "" };
      }

      const createResponse = await this.createObject({
        objectMetadata: metadata,
        hash,
        size,
        overwrite: true,
      });

      if (createResponse.ok) {
        const uploadSuccess = await uploadToPresignedUrl(
          createResponse.presignedUrl,
          tempZipPath
        );

        if (uploadSuccess) {
          if (this.isWorkspaceDir && cacheObjectId) {
            setWorkspaceObjectId(createResponse.objectId);
          }
          return { success: true, objectId: createResponse.objectId };
        } else {
          console.error("File sync failed");
          return { success: false, objectId: "" };
        }
      } else {
        console.error("File sync failed");
        return { success: false, objectId: "" };
      }
    } finally {
      // Clean up temporary file
      try {
        unlinkSync(tempZipPath);
      } catch (error) {
        console.warn(`Failed to clean up temporary file: ${error}`);
      }
    }
  }
}
